version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/API-gateway"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/auth"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/microservices/clock"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/microservices/mail"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/microservices/read"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/microservices/score"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/microservices/target"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/microservices/upload"
    schedule:
      interval: "weekly"
